### ISSUE TITLE
Known Issues and My Advice on v1.5RC5.3

### ISSUE THREAD

**Issue by NpcianT77** [ZelGimi/supersolarpanels#25]
Version: 1.5RC5.3 (1.7.10)
Here are some known issues tested on the aforementioned version, followed by a list of my other trivial advice. Some issues are serious or annoying enough to require urgent fixes.

Bugs:
* Transformer Upgrade from IC2 and Module: Panel Tier Up/Down from the mod do NOT work properly.
* Energy stoarge blocks from original IC2 (Batbox to MFSU) cannot be charged with charging items like Energy Crystal.
** The supposedly fully charged versions of them taken from creative inventory also contain no energy. 
* Energy stoarge blocks from the mod can be charged with items, but consumes their energy even when it's full.
* The lang file is filled with a load of problems, possibly requires a whole revision.
** Mispells like Sannarium (despite not being in the game), "blockTerrastelSolarPanel.name", "ssp.myphical", "earthpane", etc.
** Elemental type modules (Module: Type-Air, for example) have blank description entries. They are also not featured in the .lang file.
* All rotors from the mod show same output value (25~110MCW) from their descriptions.
* A Neutron Solar Panel causes Molecular Transformer to explode, despite higher voltage input from numerous lower tier generators doesn't do so.
* There is a tier 8 "Neutron Panel" crafted from 4 tier 9 Photonic Panels, which is certainly a glitch.
* Tier 10 Infinity Panel is crafted from 4 tier 10 Neutron Panels, but has lower efficiency.
* Panel Combiner uses panel's maximum output instead of its regular one, which makes it more than twice effective. Doesn't know if it's intentional.

Advice:
* There should be an option in the config to toggle voltage restriction.
* There shoud exist higher tier transformers.
* Molecular Transformer should uses its classic model from ASP.
* Molecular Transformer should not have a visible delay between processes.
* Higher level machines should have higher energy tiers.
* Advanced Diamond Drill made from spectral tools should be renamed to make a difference to that from Graviation Suite.
** Since advanced drills (Terrasteel Drill) can be enchanted, the aforementioned drill should have a congenital speed boost rather than Efficiency X, freeing players to enchanting it.
* Rotors, fuel rods and etc. should follow the name forms of that from IC2.
* Higher tier rotors should be more durable. (Neutron rotor, for example, has less than half the carbon rotor's durability.)
* Instant charging modules could be more expensive rather than being a no-extra-price combination of wireless and charging modules.

**Comment by ZelGimi** [comment]
1. The module Up/Down the level is needed in order to increase the level for the panel for using the module type panel 
2.very strange, everything works fine for me 
3. work fine too 
4. work fine too 
5. .lang names have been cleaned up in the new version 
6. some of them are names of items or descriptions to them, for example, Sannarium is already in the game in the new version 
7. 25-110 is the strength of the wind at which they will work 
8. fixed in new version 
9. fixed in new version 
10.  fixed in new version 
11. work fine too 
Answer
1. it has existed for a long time 
2. in the new version there are 
3. she already has her model in the new version
4. fixed in 1.5RC5.4 which is on the discord server 
5. think about it 
6. fixed
7. there may be bugs with breaking blocks 
8. fixed
9. strange, they work fine for me 
10. Well, the module itself works when you click on the energy storage, I see no reason to make it more expensive.

**Comment by ZelGimi** [comment]
All of the above has been decided.
